# Generated by Django 5.1.5 on 2025-01-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the product')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=10)),
                ('category', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids'), ('U', 'Unisex')], help_text='Product category', max_length=1)),
                ('available_sizes', models.CharField(help_text='Available sizes (comma-separated)', max_length=255)),
                ('color', models.CharField(help_text='Color of the product', max_length=50)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Stock availability')),
                ('image', models.ImageField(blank=True, help_text='Image of the product', null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True, help_text='Is the product active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the product was last updated')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
