# Generated by Django 5.1.5 on 2025-01-24 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the category was last updated')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category'),
        ),
    ]
