# Generated by Django 5.2.8 on 2025-11-14 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('unique_sessions', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('user_logins', models.IntegerField(default=0)),
                ('user_registrations', models.IntegerField(default=0)),
                ('products_viewed', models.IntegerField(default=0)),
                ('products_added_to_cart', models.IntegerField(default=0)),
                ('checkouts_completed', models.IntegerField(default=0)),
                ('cart_abandonment_rate', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CartAbandonmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('cart_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items_count', models.IntegerField(default=0)),
                ('abandoned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recovered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-abandoned_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_registered', 'User Registered'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('cart_view', 'Cart Viewed'), ('product_view', 'Product Viewed'), ('product_click', 'Product Clicked'), ('search_query', 'Search Query'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('checkout_started', 'Checkout Started'), ('checkout_completed', 'Checkout Completed'), ('menu_click', 'Menu Clicked'), ('page_view', 'Page Viewed')], db_index=True, max_length=50)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('page_url', models.URLField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='analytics_a_user_id_03d15c_idx'), models.Index(fields=['event_type', '-timestamp'], name='analytics_a_event_t_c6fe80_idx'), models.Index(fields=['session_id', '-timestamp'], name='analytics_a_session_720940_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(db_index=True, max_length=255)),
                ('click_count', models.IntegerField(default=1)),
                ('last_clicked', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'menu_item')},
            },
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('result_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['query', '-timestamp'], name='analytics_s_query_49743a_idx')],
            },
        ),
    ]
