# Generated by Django 5.2.8 on 2025-11-10 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('last_event_id', models.CharField(default='0', max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'product_id'], name='inventory_i_session_95dd83_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_available', models.IntegerField(default=0)),
                ('quantity_reserved', models.IntegerField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('stock_updated', 'Stock Updated'), ('low_stock_warning', 'Low Stock Warning'), ('out_of_stock', 'Out of Stock'), ('back_in_stock', 'Back in Stock'), ('stock_reserved', 'Stock Reserved'), ('stock_released', 'Stock Released'), ('sale_confirmed', 'Sale Confirmed')], max_length=50)),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('quantity_changed', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inventory.inventory')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory', '-created_at'], name='inventory_i_invento_da6489_idx'), models.Index(fields=['event_type', '-created_at'], name='inventory_i_event_t_c5dc40_idx')],
            },
        ),
    ]
